# 应用服务 WEB 访问端口
server:
  port: 8081
constants:
    server-name: MsHive
# 应用名称
spring:
  application:
    name: mshivebackend
  # 数据源
  data:
    mongodb:
      authentication-database: admin
      authSource: admin
      # 主机地址
      host: 47.102.196.219 #47.102.196.219
      # 数据库
      database: mshive
      # 默认端口是27017
      port: 27017
      # 用子账号
      username: root # admin
      # 用子密码
      password: je102dp20v9 #root
      # 超时时间
      socket-timeout: 1000000
      connection-timeout: 1000000
      # 也可以使用uri连接
#       uri: mongodb://admin:root@localhost:27017/mshive?authSource=admin&authentication-database=admin
  # java mail 避免邮件发送工具类写错MailSender，会和JavaMail包里的重名，从而冲突
  mail:
    host: smtp.qq.com
    protocol: smtps
    username: 2479711422@qq.com
    password: bgtzfvukfwaxecaf
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  # redis相关
  redis:
    host: 47.102.196.219
    port: 6379
    password:
    database: 0
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  # elasticsearch related
  elasticsearch:
#    username: root
#    password: root
#     es url
    uris: http://47.102.196.219:9200
#    connection timeout, default: 1s
    connection-timeout: 10s
#    data reading timeout, default: 30s
    socket-timeout: 30s
# 输出日志等级
logging:
# 	# 分组
#   group:
#     ebank: com.yimingliao.mshivebackend.controller,com.yimingliao.mshivebackend.service,com.yimingliao.mshivebackend.entity
  level:
    # root为本机调试时的输出等级，默认info
    root: info
    # ebank 为实际生产时的输出等级
    ebank: debug
#   pattern:
#     dateformat: MM-dd HH:mm:ss:SSS
#     rolling-file-name: MshiveServer.%d{yyyy-MM-dd}.%i.log # 滚动日志
#   file:
#     path: C:\Users\Lenovo\Desktop\MshiveServer\Mshive # 输出地址
#    name: MshiveServer.log
#     max-size: 1KB # 滚动大小
